# Generated by Django 5.0.5 on 2024-06-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toppage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thisweekmovies',
            name='youtube',
            field=models.TextField(max_length=10000, verbose_name='youtubeの動画id(例 https://www.youtube.com/watch?v=pjXW-hDfUzc の pjXW-hDfUzcの部分)'),
        ),
    ]
