# Generated by Django 5.0.6 on 2024-06-12 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MyMovieModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="映画名")),
                ("overview", models.CharField(max_length=10000, verbose_name="映画の概要")),
                (
                    "imagepath",
                    models.CharField(max_length=10000, verbose_name="映画の画像パス"),
                ),
                (
                    "createUser",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL, verbose_name="追加したユーザー"
                    ),
                ),
            ],
        ),
    ]
