
data = {
    "horaa_famous_new": ["It Chapter Two","それがいる森"],
    "horaa_famous_old": ["The Shining","The Sixth Sense"],
    "horaa_mania_new": ["黒い乙女A","Get Out"],
    "horaa_mania_old": ["Night of the Living Dead"],
    "action_famous_new": ["Mad Max: Fury Road","キングダム 運命の炎","Top Gun: Maverick"],
    "action_famous_old": ["Terminator 2: Judgment Day","七人の侍"],
    "action_mania_new": ["少林足球"],
    "action_mania_old": ["Commando","Predator 2"],
    "renai_famous_new": ["わたしの幸せな結婚"],
    "renai_famous_old": ["Casablanca","Roman Holiday"],
    "renai_mania_new": ["何者"],
    "renai_mania_old": ["恋人たち"],
    "sf_famous_new": ["Inception","The Matrix Resurrections","Jurassic World Dominion"],
    "sf_famous_old": ["2001: A Space Odyssey","The Matrix"],
    "sf_mania_new": ["Primer","Tenet"],
    "sf_mania_old": ["THX 1138","Кин-дза-дза!"],
    "anim_famous_new": ["Spider-Man: Beyond the Spider-Verse","劇場版 忍たま乱太郎 ドクタケ忍者隊最強の軍師","映画ドラえもん のび太の地球交響楽"],
    "anim_famous_old": ["Akira","Spirited Away"],
    "anim_mania_new": ["化け猫あんずちゃん"],
    "anim_mania_old": ["アップルシード"],
}