# Generated by Django 5.0.6 on 2024-06-19 06:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0002_rename_send_user_mail_readedmail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReadedMail",
            new_name="ReadMail",
        ),
        migrations.RenameField(
            model_name="readmail",
            old_name="readed_mail",
            new_name="read_mail",
        ),
    ]
