# Generated by Django 5.0.6 on 2024-06-19 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0003_rename_readedmail_readmail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readmail",
            name="read_mail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_mail",
                to="mail.mail",
                verbose_name="メール",
            ),
        ),
    ]
