# Generated by Django 5.0.6 on 2024-06-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0004_alter_readmail_read_mail"),
    ]

    operations = [
        migrations.AddField(
            model_name="readmail",
            name="read_count",
            field=models.IntegerField(default=0),
        ),
    ]
