# Generated by Django 5.0.6 on 2024-06-17 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("movie", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(max_length=1000, verbose_name="コメント")),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "★"),
                            (2, "★★"),
                            (3, "★★★"),
                            (4, "★★★★"),
                            (5, "★★★★★"),
                        ],
                        default="3",
                        verbose_name="レビュースコア",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="投稿日")),
                (
                    "createUser",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL, verbose_name="追加したユーザー"
                    ),
                ),
                (
                    "imagepath",
                    models.ManyToManyField(
                        related_name="imagepath_comments",
                        to="movie.mymoviemodel",
                        verbose_name="映画の画像パス",
                    ),
                ),
                (
                    "movie_name",
                    models.ManyToManyField(
                        related_name="movie_comments",
                        to="movie.mymoviemodel",
                        verbose_name="映画名",
                    ),
                ),
            ],
        ),
    ]
