# Generated by Django 5.0.6 on 2024-06-25 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 25, 9, 54, 56, 253657),
                verbose_name="投稿日",
            ),
        ),
    ]
