# Generated by Django 5.0.6 on 2024-06-19 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 19, 14, 41, 52, 180408),
                verbose_name="投稿日",
            ),
        ),
    ]
