# Generated by Django 5.0.6 on 2024-06-18 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0002_alter_comment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 18, 15, 32, 57, 899407),
                verbose_name="投稿日",
            ),
        ),
    ]
