# Generated by Django 5.0.6 on 2024-06-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0003_alter_comment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="投稿日"),
        ),
    ]
