# Generated by Django 5.0.6 on 2024-06-21 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0005_alter_comment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 21, 16, 0, 10, 839335),
                verbose_name="投稿日",
            ),
        ),
    ]
